### ISSUE TITLE
FontAwsome icons not displayed correctly

### ISSUE THREAD

**Issue by JimmyAtSchotte** [JimmyAtSchotte/scrapper#1]
When scraping https://books.toscrape.com/, the static/oscar/css/styles.css contains following css with links to font awsome fonts

``` css
@font-face {
  font-family: 'FontAwesome';
  src: url('../fonts/fontawesome-webfont.eot%3Fv=3.2.1');
  src: url('../fonts/fontawesome-webfont.eot%3F') format('embedded-opentype'), url('../fonts/fontawesome-webfont.woff%3Fv=3.2.1') format('woff'), url('../fonts/fontawesome-webfont.ttf%3Fv=3.2.1') format('truetype'), url('../fonts/fontawesome-webfont.svg') format('svg');
  font-weight: normal;
  font-style: normal;
}
```

They get downloaded correctly, but they cant be found when running the website under file:/// protocol.

I suspect it has something to do with the Url encoded ? (%3F) in the urls.
